apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: 875206965122.dkr.ecr.us-east-2.amazonaws.com/eks-demo/db:latest
          ports:
            - containerPort: 3306