apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: app
          image: 875206965122.dkr.ecr.us-east-2.amazonaws.com/eks-demo/app:latest
          ports:
            - containerPort: 5000
        - name: app2
          image: 875206965122.dkr.ecr.us-east-2.amazonaws.com/eks-demo/app2:latest
          ports:
            - containerPort: 5001